apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-2
  labels:
    app: sample-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-2
  template:
    metadata:
      labels:
        app: sample-app-2
    spec:
      containers:
      - name: sample-app-2
        image: asia-northeast1-docker.pkg.dev/taro-demo/handson/testapp:v1
        resources:
          limits:
            cpu: "250m"
          requests:
            cpu: "250m"
        ports:
        - containerPort: 8080
